baseURL: https://literate-devops.io/
theme: risotto-solarized
title: Literate DevOps
author: James Hilling
copyright: © 2023 James Hilling
DefaultContentLanguage: en
languageCode: en
enableEmoji: true
enableInlineShortcodes: true
ignoreErrors:
- error-remote-getjson
menu:
  main:
  - identifier: cv
    name: CV
    url: /cv/
    weight: 10
  - identifier: portfolio
    name: Portfolio
    url: /portfolio/
    weight: 20
paginate: 3
params:
  about:
    description: Currently preparing for the certified Kubernetes administrator exam (with four years of professional experience with Kubernetes). Part time Emacs and literate DevOps enthusiast.
    logo: images/console-red.svg
    title: James Hilling BSc
  socialLinks:
  - icon: "fa-brands fa-github"
    title: GitHub
    url: https://github.com/James5979
  - icon: "fa-solid fa-envelope"
    title: Email
    url: mailto:literate-devops@use.startmail.com
  - icon: "fa-solid fa-comment"
    title: Mastodon
    url: "https://mastodon.social/@james5979"
  noindex: false
  theme:
    mode: dark-mode
    palette: solarized-dark
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    style: solarized-dark
sectionPagesMenu: main
taxonomies:
  category: categories
  series: series
  tag: tags
